.TH LIBPNGPF 3 "April 6, 2009"
.SH NAME
libpng \- Portable Network Graphics (PNG) Reference Library 1.2.36beta04
(private functions)
.SH SYNOPSIS
.SH DESCRIPTION
The functions listed above are used privately by libpng
and are not recommended for use by applications.  They are
not "exported" to applications using shared libraries.  They
are listed alphabetically here as an aid to libpng maintainers.
See png.h for more information on these functions.

.SH SEE ALSO
.IR libpng(3) ", " png(5)
.SH AUTHOR
Glenn Randers-Pehrson
