#!/bin/sh
echo 'Testing uncompressed text chunk - tEXT (plain format)'
INPUT=ct1n0g04.png
OUTPUT=test1.xpt

for dir in . ..; do
  if [ -r $dir/$OUTPUT ]; then
    break;
  fi
done
here=`pwd`
cd $dir && $here/pngmeta -quiet $INPUT | diff -c $OUTPUT -
