
/*-
 * config.h
 *
 * Copyright (c) 2011 John Cunningham Bowler
 *
 * Last changed in libpng 1.6.0 [(PENDING RELEASE)]
 *
 * This code is released under the libpng license.
 * For conditions of distribution and use, see the disclaimer
 * and license in png.h
 *
 * Use the "config.h" generated by configure for libpng.  For indpendent
 * compilation of the .c files in this directory either make an appropriate
 * configure script to generate config.h or do not define HAVE_CONFIG_H.
 */
#include "../../bsconfig.h"
