# Copyright (C) 2024 Cosmin Truta
# SPDX-License-Identifier: MIT-0

name: Linting libpng

on:
  push:
    branches:
      - libpng16
      - libpng18
  pull_request:
    branches:
      - libpng16
      - libpng18

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up the cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pip.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install yamllint
        run: pip install yamllint
      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # main
      - name: Check out the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run the linting script
        run: bash ./ci/ci_lint.sh
